apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .Values.kindSetName }}
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/michaelkotelnikov/argocd-bench-list-generator.git
      revision: master
      files:
        - path: 'kinds/*_cr.yaml'
  template:
    metadata:
      name: '{{ .Values.projectName }}-{{ "{{ metadata.name }}" }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/michaelkotelnikov/argocd-bench-list-generator.git
        targetRevision: master
        path: appset/
        helm:
          valueFiles:
          - 'values.yaml'
          parameters:
            - name: global.clusterName
              value: '{{ "{{ metadata.name }}" }}'
      destination:
        name: 'in-cluster'
      syncPolicy:
        automated:
          prune: false
          selfHeal: true